<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <LangVersion>latestmajor</LangVersion>
    </PropertyGroup>

    <ItemGroup>
      <FrameworkReference Include="Microsoft.AspNetCore.App" />
    </ItemGroup>

    <ItemGroup>
      <Using Include="Microsoft.Extensions.DependencyInjection" />
      <Using Include="Microsoft.Extensions.Hosting" />
      <Using Include="Microsoft.Extensions.Logging" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Magick.NET-Q16-AnyCPU" Version="14.17.1" />
      <PackageReference Include="MetadataExtractor" Version="2.9.3" />
      <PackageReference Include="SkiaSharp" Version="4.152.1" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\PhotoMap.Shared\PhotoMap.Shared.csproj" />
    </ItemGroup>

</Project>
