<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <LangVersion>latestmajor</LangVersion>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\PhotoMap.Shared\PhotoMap.Shared.csproj" />
      <ProjectReference Include="..\PhotoMap.Api.Database\PhotoMap.Api.Database.csproj" />
      <ProjectReference Include="..\PhotoMap.Api.Domain\PhotoMap.Api.Domain.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Dropbox.Api" Version="7.0.0" />
      <PackageReference Include="Magick.NET-Q16-x64" Version="13.9.0" />
      <PackageReference Include="MetadataExtractor" Version="2.8.1" />
      <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="8.0.1" />
      <PackageReference Include="SkiaSharp" Version="2.88.8" />
    </ItemGroup>

    <ItemGroup>
      <Reference Include="Microsoft.Extensions.DependencyInjection.Abstractions">
        <HintPath>..\..\..\..\..\..\..\usr\local\share\dotnet\shared\Microsoft.AspNetCore.App\7.0.1\Microsoft.Extensions.DependencyInjection.Abstractions.dll</HintPath>
      </Reference>
    </ItemGroup>

</Project>
